### ISSUE TITLE
Please provide answers also..

### ISSUE THREAD

**Issue by kartheekjonnalagadda** [Yonet/Angular-Interview-Questions#16]

**Comment by devquora** [comment]
You can find answers of These angular js questions from 
https://www.devquora.com/angularjs

**Comment by ArcheGalla** [comment]
It would be nice at least links to docs, where you can find answers

**Comment by Yonet** [comment]
Some of the questions have answers on the related readme doc. You can find the rest at [Angular docs](https://next.angular.io/)
