### ISSUE TITLE
Where are the answers?

### ISSUE THREAD

**Issue by LordJohn42** [Yonet/Angular-Interview-Questions#32]
Hey guys, question answers is needed.

**Comment by Yonet** [comment]
Hey @LordJohn42, I am not a guy. 
You can find some of the hard to find answers in the folders. Others answers can be found on the docs. If you have any specific question that you are not able to find the answer, please specify. I can add the answer to your specific question.

**Comment by Yonet** [comment]
I am closing this issue, feel free to open an issue with a specific question.

**Comment by LordJohn42** [comment]
Thank you @Yonet. Sorry for my omission.
