### ISSUE TITLE
Invalid example in API Questions

### ISSUE THREAD

**Issue by ericmartinezr** [Yonet/Angular-Interview-Questions#8]
Under [API Questions](https://github.com/Yonet/Angular-Interview-Questions#api-questions) there's this example

```typescript
@HostBinding('[class.valid]') isValid;
```

When using HostBinding the brackets `[]` are implicit. Actually if you run that code it will fail. The valid example is  `@HostBinding('class.valid')...`

Now, if the purpose of that question is to trick the interviewee on purpose I just failed the interview :P

**Comment by Yonet** [comment]
Awesome, thank you for the pull request.
